---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/partners
  label: Partners
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: content/en-us/blog
  label: Blog - English
  create: all
  match: "**/*"
- type: directory
  path: content/en-us/shop
  label: Shop - English
  create: all
  match: "**/*"
- type: directory
  path: content/fr-fr/shop
  label: Shop - Francais
  create: all
  match: "**/*"
- type: directory
  path: content/fr-fr/blog
  label: Blog - Francais
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
